spring:
  datasource:
    driverClassName: org.h2.Driver
    initialization-mode: never
    url: jdbc:mysql://localhost:3306/weby?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none