crawler:
  cron:
    expression: '0 */15 * * * *'
  articleIdForThumbQueueSize: 10
  thumbResizeLoopMillisecondDelay: 500
  headLinesBySitePool: 1

spring:

  profiles:
      include: h2

  logging:
    level:
      com.crevainera.weby: DEBUG